Ft contact modal
devPinheiro/cribsandspaces pull request #38
Opened 2020-02-12 21:55 UTC by itolimaesther

**What does this PR do?** 
It contains a feature of a user contacting the team.

** How should this be manually tested?** 
After cloning the repo, cd into the folder and RUN Install all necessary dependencies by running npm install Launch the node server with npm run dev Using a web browser visit the link below:** http://localhost:3500 To run local tests using Jest npm test

 **Any background context you want to provide?**
 N/A 
**What are the relevant pivotal tracker stories?** 
PT Story link - [#167590396] (https://www.pivotaltracker.com/story/show/167590396)

2020-02-12 22:42 UTC, devPinheiro requested changes

2020-02-12 22:42 UTC, devPinheiro commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
Hi Esther, I see you imported Apollo-boost here. why did you import it here?

2020-02-15 14:13 UTC, itolimaesther commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
I can't remember importing that. It is not my code.

2020-02-15 21:24 UTC, devPinheiro commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
Alright, I will need you to remove that line of code since we are not using it. Thank you

2020-02-15 21:26 UTC, devPinheiro requested changes
Esther, you are doing a good job. Kindly smash your commits into one commit message. Kindly reach out to me if you need any help with this.🚀🚀

2020-02-21 01:14 UTC, itolimaesther commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
Done.

2020-02-21 01:54 UTC, itolimaesther commented
> Esther, you are doing a good job. Kindly smash your commits into one commit message. Kindly reach out to me if you need any help with this.

Done

2020-02-21 15:16 UTC, devPinheiro commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
🚀🚀

2020-02-22 01:13 UTC, MrDiamond007 approved these changes

2020-02-22 01:15 UTC, 2unasty commented on src/client/components/Header/index.js
> +import { from } from 'apollo-boost';
nice

2020-02-22 08:08 UTC, devPinheiro requested changes
Kindly rebase your branch against master as there are some merge conflicts. Thank you

2020-02-22 08:08 UTC, devPinheiro commented on .travis.yml
> +script: npm run test:coverage
Hey Esther, can you take out this line of code. We have not setup test coverage yet thanks

2020-02-25 11:15 UTC, closed without merging